name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ninja
      run: choco install ninja

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglm-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Install GLFW
      run: |
        wget https://github.com/glfw/glfw/releases/download/3.3.9/glfw-3.3.9.zip
        unzip glfw-3.3.9.zip -d thirdparty/
        cd thirdparty/glfw-3.3.9
        mkdir build
        cd build
        cmake ..
        make

    - name: Install GLAD
      run: |
        git clone https://github.com/Dav1dde/glad.git thirdparty/glad
        cd thirdparty/glad
        cmake .
        make

    - name: Install STB
      run: |
        mkdir -p thirdparty/stb
        wget -O thirdparty/stb/stb.h https://raw.githubusercontent.com/nothings/stb/master/stb.h
        touch thirdparty/stb/stb.cpp

    - name: Build
      run: .\build.bat -r

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}