name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Ninja
      run: choco install ninja

    - name: Install GLFW
      run: |
        Invoke-WebRequest -Uri https://github.com/glfw/glfw/releases/download/3.3.9/glfw-3.3.9.zip -OutFile glfw-3.3.9.zip
        Expand-Archive glfw-3.3.9.zip -DestinationPath thirdparty/
        cd thirdparty/glfw-3.3.9
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Install GLAD
      run: |
        git clone https://github.com/Dav1dde/glad.git thirdparty/glad
        cd thirdparty/glad
        cmake .
        cmake --build .

    - name: Install STB
      run: |
        mkdir -p thirdparty/stb
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/nothings/stb/master/stb.h -OutFile thirdparty/stb/stb.h
        New-Item -Path thirdparty/stb/stb.cpp -ItemType "file"

    - name: Build
      run: .\build.bat -r

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
